# Site settings
title: xinyu wang
email: hello@xinyudesign.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Web & UI designer currently located in Austin, TX.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xinyudesign.com" # the base hostname & protocol for your site
twitter_username: xinyu0
github_username:  xinyu0
dribbble_username: xinyu0

# Build settings
markdown: kramdown
